import type { Metadata } from "next";
import "@/interface/styles/globals.css";
import { ENV_UI } from "@/env/ui";
import { geistMono, geistSans } from "@/interface/fonts/main";

export const metadata: Metadata = {
	title: ENV_UI.APP_NAME,
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
